[package]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
dotenv = "0.15.0"
smtp = {path = "../smtp"}
imap = {path = "../imap"}
ratatui = {version = "0.28.1", features = ["all-widgets"]}
